#########################################################################
# Â© Ronan LE MEILLAT 2023
# released under the GPLv3 terms
#########################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: deployment-easyappointments
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: easyappointments-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: easyappointments-server
    spec:
      containers:
        - env:
            - name: BASE_URL
              value: {{ .Values.deploymentEasyappointment.baseUrl }}
            - name: LANGUAGE
              value: {{ .Values.deploymentEasyappointment.language }}
            - name: DEBUG
              value: {{ squote .Values.deploymentEasyappointment.debug }}
            - name: DB_HOST
              value: {{ .Values.deploymentEasyappointment.dbhost }}
            - name: DB_NAME
              value: {{ .Values.deploymentEasyappointment.dbname }}
            - name: DB_USERNAME
              value: {{ .Values.deploymentEasyappointment.dbusername }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: root
                  name: mysql-credentials
            - name: GOOGLE_SYNC_FEATURE
              value: {{ squote .Values.deploymentEasyappointment.googleSync }}
            - name: GOOGLE_PRODUCT_NAME
            - name: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
            - name: GOOGLE_API_KEY
          image: {{ print .Values.deploymentEasyappointment.image ":" .Values.deploymentEasyappointment.imageTag }}
          imagePullPolicy: IfNotPresent
          name: easyappointments-server
          ports:
            - containerPort: 8888
              protocol: TCP
          resources:
            limits:
              cpu: '2'
              memory: 1Gi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
