#########################################################################
# Â© Ronan LE MEILLAT 2023
# released under the GPLv3 terms
#########################################################################
apiVersion: v1
kind: Secret
metadata:
  name: secrets-smtpd

stringData:
  cloudflare-api_key: {{ quote .Values.smtpd.cloudflareApiKey }}
  cloudflare-zone-id: {{ quote .Values.smtpd.cloudflareZoneId }}
  smtpd-dkim-private-key: {{ quote .Values.smtpd.smtpdDkimPrivateKey }}
type: Opaque
---