#########################################################################
# Â© Ronan LE MEILLAT 2023
# released under the GPLv3 terms
#########################################################################
apiVersion: v1
kind: Service
metadata:
  name: smtpd
  labels:
    io.kompose.service: smtpd
spec:
  type: {{ .Values.smtpd.type }}
  selector:
    io.kompose.service: smtpd

  ports:
	{{- .Values.smtpd.ports | toYaml | nindent 2 -}}